title: Juan Fernando Pinzon
logo: /assets/img/photo_round.png
description: > 
  Data Scientist and Machine Learning Researcher/Developer.
  <br><br>
  M.Sc Big Data Analytics & AI, Business Administration bachelor.
  <br><br>
  [<img src="/assets/logos/linkedin.jpeg">](https://www.linkedin/in/juanfpinzon/)
  <a href="https://www.linkedin.com/in/juanfpinzon/">View My LinkedIn Profile</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
