title: Juan Fernando Pinzon
logo: /assets/img/photo.png
description: > 
  Data Scientist and Machine Learning Researcher/Developer.
  <br><br>
  M.Sc Big Data Analytics & AI, Business Administration bachelor.
  <br><br>
  <a href="https://www.linkedin.com/in/juanfpinzon/">View My LinkedIn Profile</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
