title: Juan Fernando Pinzon
logo: /assets/img/photo_round.png
description: > 
  Data Scientist and Machine Learning Researcher/Developer.
  <br><br>
  M.Sc Big Data Analytics & AI, Business Administration bachelor.
  <br><br>
  <a href="mailto:juancho704@gmail.com">
    <img src="/assets/logos/email.png" alt="Email" style="width:42px;height:42px;">
  </a>
  <a href="https://www.linkedin.com/in/juanfpinzon/">
    <img src="/assets/logos/linkedin.jpeg" alt="LinkedIn" style="width:42px;height:42px;">
  </a>
  <br><br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
