title: Juan Fernando Pinzon
logo: /assets/img/photo_round.png
description: > 
  <br>
  <p align="justify">
  Data Scientist and Machine Learning Researcher/Developer.
  <br><br>
  M.Sc Big Data Analytics & AI, Business Administration bachelor.
  <br><br>
  </p>
  <p align="center">
  <a href="/docs/Resume-Juan-Pinzon_11.09.21.pdf">
    <img src="/assets/logos/cv.png" alt="CV Download" style="width:42px;height:42px;">
  </a>
  <a href="mailto:juancho704@gmail.com" target="_blank" rel="noopener noreferrer">
    <img src="/assets/logos/email.png" alt="Email" style="width:42px;height:42px;">
  </a>
  <br>
  <a href="https://www.linkedin.com/in/juanfpinzon/" target="_blank" rel="noopener noreferrer">
    <img src="/assets/logos/linkedin.jpeg" alt="LinkedIn" style="width:42px;height:42px;">
  </a>
  <br>
  <a href="https://github.com/juanfpinzon" target="_blank" rel="noopener noreferrer">
    <img src="/assets/logos/github.png" alt="GitHub" style="width:42px;height:42px;">
  </a>
  <br><br>
  </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
